"""add ai_summary column to article table

Revision ID: c8f1f9be9c58
Revises: 6c0f978c0113
Create Date: 2025-09-10 21:51:52.759279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f1f9be9c58'
down_revision = '6c0f978c0113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'ai_summary')
    # ### end Alembic commands ###
